spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: prepelicamangalica
    password: root
    url: jdbc:postgresql://localhost:5432/dogetip
    platform: postgresql
    initialization-mode: always
    continue-on-error: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
server:
  port: 8090
twilio:
  account_sid: ${accountSid} #your account sid
  auth_token: ${authToken} #your auth token
  trial_number: ${trialNumber} # your trial number
