spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: prepelicamangalica
    password: root
    url: jdbc:postgresql://localhost:5432/dogetip
    platform: postgresql
    initialization-mode: always
    continue-on-error: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql