spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: prepelicamangalica
    password: root
    url: jdbc:postgresql://localhost/postgres
    platform: dogetip
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql